dist: trusty
sudo: false
language: go
go:
- 1.11.x
after_success:
- bash <(curl -s https://codecov.io/bash)
install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
script:
- make travis
deploy:
  provider: releases
  api_key:
    secure: cAz8q26sjVQpXdlwqmY7hs+RBS29CbXXVAtWE2NTsVeE4eibNo31N+9FPjhSruE+jk9hWQZboBiDLiCenABMFxyrAvZFjVU8X2FW0iEXg/NbcP/YqXh2Wav+/Di1O8z/A8g/Lz9TCDjv9+3g02wy7JIvPLYK+FiyjW4bw0GAFNK2nLRZ1G4EDqGiwSwh4ZKSVg7Ps/0xWtfRHJ/uVWWYNBVw0jkH7METIzGMwGOSaccSx4YsCQOcC8fnk6XJxduIO/YqqHtJ7TUj+EHYd+N9q/Tx+m6cs0TnMWRdDblHDJG3NqSuLclyak3kxQWIkJsfcUZ5jyjxKKVnAD7HIShT0nKRJ0Sb7uy8AipdD3S6C4rg9/shL3UkNo+jyL1uhliVNGQicPb/XqcGw6jSi2Td19lnKJ3OE7kiTuU0v9fjn7molWILXvB1TUNcuQuFRdu+MXp3QxARC0bg/dkINeaKj3e9SaSNSRmq1eADNjlMK38FWBnWI6yaofq5P2IwW730bZXfWaaGqe6j0SCd5D7mZMcvyfnvauhoKaC4cCLJ6wdwrZlNM5kpQd9NEkogRfrCH1dFvkr5mmgUX3WE2iBC/KI/wcSee6RyiygBHkSLGn5t1J9dzFwM1hRIDwMP0CNx56Jrv79Kl9Tw/ibvd6XyGyjBR8+DH/6jpDj+xE5afWM=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: moussetc/mattermost-plugin-spoiler
    tags: true
env:
  global:
  - secure: d6Ewypip4jAyoS3dh2CrXWWWFYdfNtOVQ6STHXR8VjfIGXlQDxzyD3CXC3YklCBvtwwy6fnntTgiPlkBjXWxfAGcaRB2RUBibfNe2HsyozYVcFS4Dk8M5sLNTIeHGuHXolhy7ds0beian9chOO6We8PghY9y4DnjZPHrwN3sKCVJLgxsoBklcOxZ4XrNNou6j8HzgD/kLz7u4MZR7wtG7Ds6SoX71DCvjFuKFr96/qggwo574IU9cKqEnFMNiD5jlygMYtCx9e9fbtOf5VkiaI3siH0G648flg9FHoI1yAb5r+2NEbgdcoxoHQ0FmZMQm9iXTxhkKD2l+j3pMvnFWhl8E8lNBH/ZSckStuKXT6YSNH7nz1ACyf/iDYyE+JRcWk6uo9SswaMNZEPryRxuNaXKXzyK+ga7nNu4EHQI5+AtUCg2VdMmgFHFeHT5ApeX572rGHKOUh8rbVFkyCM9WGnt9+AiD/Q/49g1lbrDNPSCyi4VKHl+53TmMuW8ESgkSc0Sn+87SjkF/XgAOchXhF0WjN+G5VRGN+aJKf+CqQ4hD0lC777qNYaZaLd0qYq8Kw+G0cggCqtKVDMAGd3M8seJ7gEnb7Lq39VgErgmTw5qGomgH5KKSY7Dp+PUkjamV+XJBxM37UmfZo3ZDueJUZdA5jBP6gjzZzQ1689jT5o=
